### ISSUE TITLE
Can't compile the example model in MATLAB 2019b

### ISSUE THREAD

**Issue by freemank1224** [kyak/stellaris_ert#1]
When I try to build the example model (use Ctrl+B), it shows:
`C:\Users\Dyson\AppData\Roaming\MathWorks\MATLAB Add-Ons\Collections\Simulink (Embedded Coder) Target for TI Stellaris LaunchPad\stellaris_test_blink_stellaris>set MATLAB=C:\Program Files\MATLAB\R2019b 

C:\Users\Dyson\AppData\Roaming\MathWorks\MATLAB Add-Ons\Collections\Simulink (Embedded Coder) Target for TI Stellaris LaunchPad\stellaris_test_blink_stellaris>"C:\Program Files\MATLAB\R2019b\bin\win64\gmake" -f stellaris_test_blink.mk  GENERATE_ASAP2=0 ISPROTECTINGMODEL=NOTPROTECTING 
stellaris_test_blink.mk:325: warning: overriding commands for target `stellaris_test_blink'
stellaris_test_blink.mk:296: warning: ignoring old commands for target `stellaris_test_blink'
cc -c -I. -I.. -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/ert -IC:/PROGRA~1/MATLAB/R2019b/extern/include -IC:/PROGRA~1/MATLAB/R2019b/simulink/include -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/src -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/src/ext_mode/common -IC:/Users/Dyson/AppData/Roaming/MATHWO~1/MATLAB~1/COLLEC~1/SIMULI~1 -IC:/Users/Dyson/AppData/Roaming/MATHWO~1/MATLAB~1/COLLEC~1/SIMULI~1/stellaris_test_blink_stellaris -IC:/PROGRA~1/MATLAB/R2019b/extern/include -IC:/PROGRA~1/MATLAB/R2019b/simulink/include -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/src -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/src/ext_mode/common -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/ert -IC:/Users/Dyson/AppData/Roaming/MATHWO~1/MATLAB~1/COLLEC~1/SIMULI~1/blocks       main_stellaris_test_blink.c main_stellaris_test_blink 
process_begin: CreateProcess(NULL, cc -c -I. -I.. -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/ert -IC:/PROGRA~1/MATLAB/R2019b/extern/include -IC:/PROGRA~1/MATLAB/R2019b/simulink/include -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/src -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/src/ext_mode/common -IC:/Users/Dyson/AppData/Roaming/MATHWO~1/MATLAB~1/COLLEC~1/SIMULI~1 -IC:/Users/Dyson/AppData/Roaming/MATHWO~1/MATLAB~1/COLLEC~1/SIMULI~1/stellaris_test_blink_stellaris -IC:/PROGRA~1/MATLAB/R2019b/extern/include -IC:/PROGRA~1/MATLAB/R2019b/simulink/include -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/src -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/src/ext_mode/common -IC:/PROGRA~1/MATLAB/R2019b/rtw/c/ert -IC:/Users/Dyson/AppData/Roaming/MATHWO~1/MATLAB~1/COLLEC~1/SIMULI~1/blocks main_stellaris_test_blink.c main_stellaris_test_blink, ...) failed.
make (e=2): 系统找不到指定的文件。
gmake: *** [main_stellaris_test_blink] Error 2

Error(s) encountered while building "stellaris_test_blink"
Component:Simulink | Category:Block diagram error`

I check the Setting menu and find it's alittle wired since there is no target board connection setting, could you tell me what should I do next? Thanks

**Comment by kyak** [comment]
This support package is not supposed to be installed from MATLAB Add-ons. This workflow has never been tested. Please refer to README.md for installation steps.

Your particular problem is due to the fact that you haven't specified path to CCS compiler. This is something that you would've done if you were to follow installation instructions.

**Comment by freemank1224** [comment]
Thanks for your quickly response. I think the only step I omitted is compile some example project in CCS. I'll try that ,thanks
